-- +goose Up
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    parent_id BIGINT NULL REFERENCES departments(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT departments_name_not_empty CHECK (length(trim(name)) > 0),

    CONSTRAINT departments_parent_not_self CHECK (id <> parent_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS departments_parent_name_unique
ON departments (COALESCE(parent_id, 0), lower(name));

-- +goose Down
DROP INDEX IF EXISTS departments_parent_name_unique;
DROP TABLE IF EXISTS departments;
