-- +goose Up
CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
    full_name VARCHAR(200) NOT NULL,
    position VARCHAR(200) NOT NULL,
    hired_at DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT employees_full_name_not_empty CHECK (length(trim(full_name)) > 0),
    CONSTRAINT employees_position_not_empty CHECK (length(trim(position)) > 0)
);

-- +goose Down
DROP TABLE IF EXISTS employees;
